-- SQL 01_SELECT
SELECT * FROM TB_CLASS tc ;
SELECT * FROM TB_DEPARTMENT td;
SELECT * FROM TB_CLASS_PROFESSOR tcp;
SELECT * FROM TB_GRADE tg ;
SELECT * FROM TB_PROFESSOR tp ;
SELECT * FROM TB_STUDENT ts ;

SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT td;


SELECT CLASS_NAME, '의 정원은' ,CAPACITY , '명 입니다'
FROM TB_DEPARTMENT MAIN
NATURAL JOIN TB_CLASS tc ;

SELECT STUDENT_NAME
FROM TB_DEPARTMENT td 
NATURAL JOIN TB_STUDENT ts 
WHERE DEPARTMENT_NAME LIKE '국어국문학과%'
AND STUDENT_NAME LIKE '한수_%';

SELECT STUDENT_NO
FROM TB_STUDENT ts 
WHERE STUDENT_NAME LIKE '홍경희'
OR  STUDENT_NAME LIKE '최경희'
OR  STUDENT_NAME LIKE '정경훈'
OR  STUDENT_NAME LIKE '정경환'
OR  STUDENT_NAME LIKE '이경환';

SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT td 
WHERE CAPACITY >=20 OR CAPACITY <=30;

SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR tp 
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE  STUDENT_NAME IS NULL;

SELECT PREATTENDING_CLASS_NO 
FROM TB_CLASS tc 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT td
ORDER BY CATEGORY DESC;

SELECT STUDENT_NO , STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'N';

-- SQL02_

--문제1
SELECT STUDENT_NO "학번",STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT 
WHERE  DEPARTMENT_NO LIKE'001%';

--문제2
SELECT PROFESSOR_NAME ,PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE PROFESSOR_NAME NOT LIKE '___%' ;

--문제3
SELECT PROFESSOR_NAME "교수이름" , FLOOR(MONTHS_BETWEEN(SYSDATE, 
TO_DATE(SUBSTR(PROFESSOR_SSN , 1, 6), 'RRMMDD')) / 12) "나이"
FROM TB_PROFESSOR tp ;

--문제4
SELECT  SUBSTR(PROFESSOR_NAME,2,2) "이름"
FROM TB_PROFESSOR tp 
; 


--문제5
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
- LPAD(SUBSTR(STUDENT_SSN, 1, 2), 4, '19') >= 20;


-- 문제6
SELECT TO_CHAR(to_date(20201225), 'day') FROM dual;

-- 문제7
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL; -- 2099년 10월 11일
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL; -- 2049년 10월 11일
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL; -- 1999년 10월 11일
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL; -- 2049년 10월 11일

-- 문제8
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 문제9

SELECT ROUND(AVG(POINT), 1) 평점 FROM TB_GRADE 
WHERE STUDENT_NO = 'A517178';

-- 문제10

SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)" FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO 
ORDER BY 1 ;

-- 문제 11
SELECT COUNT(*) 
FROM TB_STUDENT 
WHERE COACH_PROFESSOR_NO IS NULL;

-- 문제 12
SELECT SUBSTR() 









